// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Vincent_OS_App_Registry_1_H
#define WINRT_Vincent_OS_App_Registry_1_H
#include "winrt/impl/Vincent_OS_App_Registry.0.h"
WINRT_EXPORT namespace winrt::Vincent_OS_App_Registry
{
    struct __declspec(empty_bases) IClass :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IClass>
    {
        IClass(std::nullptr_t = nullptr) noexcept {}
        IClass(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
