// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Vincent_OS_App_Registry_2_H
#define WINRT_Vincent_OS_App_Registry_2_H
#include "winrt/impl/Vincent_OS_App_Registry.1.h"
WINRT_EXPORT namespace winrt::Vincent_OS_App_Registry
{
    struct __declspec(empty_bases) Class : winrt::Vincent_OS_App_Registry::IClass
    {
        Class(std::nullptr_t) noexcept {}
        Class(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Vincent_OS_App_Registry::IClass(ptr, take_ownership_from_abi) {}
        Class();
    };
}
#endif
