// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

void* winrt_make_Vincent_OS_App_Registry_Class()
{
    return winrt::detach_abi(winrt::make<winrt::Vincent_OS_App_Registry::factory_implementation::Class>());
}
WINRT_EXPORT namespace winrt::Vincent_OS_App_Registry
{
    Class::Class() :
        Class(make<Vincent_OS_App_Registry::implementation::Class>())
    {
    }
}
