// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Vincent_OS_App_Registry_H
#define WINRT_Vincent_OS_App_Registry_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.220531.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.220531.1"
#include "winrt/impl/Vincent_OS_App_Registry.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_Vincent_OS_App_Registry_IClass<D>::MyProperty() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Vincent_OS_App_Registry::IClass)->get_MyProperty(&value));
        return value;
    }
    template <typename D> auto consume_Vincent_OS_App_Registry_IClass<D>::MyProperty(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Vincent_OS_App_Registry::IClass)->put_MyProperty(value));
    }
    template <typename D>
    struct produce<D, winrt::Vincent_OS_App_Registry::IClass> : produce_base<D, winrt::Vincent_OS_App_Registry::IClass>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::Vincent_OS_App_Registry
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Vincent_OS_App_Registry::IClass> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Vincent_OS_App_Registry::Class> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
